# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leilighet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leil', models.CharField(max_length=20)),
                ('kvadrat', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fnavn', models.CharField(max_length=40)),
                ('enavn', models.CharField(max_length=60)),
                ('telefon', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('gateaddresse', models.CharField(max_length=40)),
                ('byaddresse', models.CharField(max_length=40)),
                ('note', models.CharField(max_length=240)),
            ],
        ),
        migrations.CreateModel(
            name='Rolle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relasjon', models.CharField(max_length=40)),
                ('betaling', models.IntegerField()),
                ('personer', models.ManyToManyField(to='bolig.Person')),
            ],
        ),
        migrations.AddField(
            model_name='leilighet',
            name='personer',
            field=models.ManyToManyField(to='bolig.Person'),
        ),
    ]
