# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolig', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='byaddresse',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='gateaddresse',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='note',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='telefon',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rolle',
            name='betaling',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rolle',
            name='personer',
            field=models.ManyToManyField(blank=True, null=True, to='bolig.Person'),
        ),
    ]
