# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolig', '0002_auto_20160327_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='byaddresse',
        ),
        migrations.RemoveField(
            model_name='person',
            name='gateaddresse',
        ),
        migrations.RemoveField(
            model_name='person',
            name='note',
        ),
        migrations.RemoveField(
            model_name='person',
            name='telefon',
        ),
        migrations.AlterField(
            model_name='rolle',
            name='personer',
            field=models.ManyToManyField(blank=True, to='bolig.Person'),
        ),
    ]
