# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolig', '0003_auto_20160327_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='byaddresse',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='person',
            name='gateaddresse',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='person',
            name='note',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='person',
            name='telefon',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
