# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 14:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bolig', '0005_remove_leilighet_personer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rolle',
            name='personer',
        ),
    ]
