# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 14:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bolig', '0006_remove_rolle_personer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='note',
        ),
    ]
