# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 14:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bolig', '0007_remove_person_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='email',
        ),
    ]
