# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolig', '0009_auto_20160327_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='leilighet',
            name='personer',
            field=models.ManyToManyField(to='bolig.Person'),
        ),
        migrations.AddField(
            model_name='person',
            name='byaddresse',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='gateaddresse',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='person',
            name='note',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='person',
            name='telefon',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='rolle',
            name='personer',
            field=models.ManyToManyField(blank=True, to='bolig.Person'),
        ),
    ]
