# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolig', '0010_auto_20160327_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rolle',
            name='personer',
        ),
        migrations.AddField(
            model_name='person',
            name='personer',
            field=models.ManyToManyField(blank=True, to='bolig.Rolle'),
        ),
    ]
