# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 21:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bolig', '0011_auto_20160327_2256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='personer',
            new_name='roller',
        ),
    ]
