# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 23:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bolig', '0012_auto_20160327_2349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='note',
        ),
    ]
