# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolig', '0013_remove_person_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='note',
            field=models.CharField(blank=True, max_length=240),
        ),
    ]
