# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-18 13:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bolig', '0018_auto_20160331_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolle',
            name='bullshit',
            field=models.CharField(default=datetime.datetime(2016, 4, 18, 13, 45, 52, 646648, tzinfo=utc), max_length=10),
            preserve_default=False,
        ),
    ]
