# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-19 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolig', '0022_remove_linker_minsak'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bortleid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leil', models.CharField(max_length=20)),
                ('kvadrat', models.IntegerField()),
            ],
        ),
    ]
