# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-19 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolig', '0023_bortleid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bortleid',
        ),
        migrations.RemoveField(
            model_name='rolle',
            name='bullshit',
        ),
        migrations.AddField(
            model_name='rolle',
            name='logo',
            field=models.URLField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='rolle',
            name='note',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
