# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-20 20:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bolig', '0026_auto_20160419_2255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Innlegg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('tekst', models.TextField()),
                ('created_date', models.DateTimeField(default=datetime.datetime(2016, 4, 20, 20, 37, 24, 540277, tzinfo=utc))),
                ('tillatsvar', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kat', models.CharField(max_length=40)),
                ('type', models.CharField(blank=True, max_length=12)),
                ('logo', models.FileField(blank=True, max_length=80, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Kommentar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=80)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='svar', to='bolig.Innlegg')),
            ],
        ),
        migrations.RemoveField(
            model_name='rolle',
            name='logo',
        ),
        migrations.AlterField(
            model_name='person',
            name='note',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rolle',
            name='note',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='innlegg',
            name='kategori',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kats', to='bolig.Kategori'),
        ),
    ]
