# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-05 09:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bolig', '0027_auto_20160420_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='innlegg',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
